server:
  port: 8080
spring:
  application:
    name: spring-consumer
  cloud:
    stream:
      bindings:
        myInput:
          group: groupA
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest