spring:
  cloud:
    gateway:
      locator:
        enabled: true
        #全局过滤器将所有的响应加上头部X-Response-Default-Foo: Default-Bar。
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      #定义了id为default_path_to_http的路由，只是优先级比较低，当该请求都不能匹配时，将会转发到blueskykong.com。
      - id: default_path_to_http
        uri: blueskykong.com
        order: 10000
        predicates:
        - Path=/**
      #路由定义了，所有请求路径以/user开头的请求，都将会转发到user服务，并应用路径的过滤器，截取掉路径的第一部分前缀。
      #即访问/user/test的实际请求转换成了lb://user/test。
      - id: service_to_user
        uri: lb://user
        order: 8000
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
     # webSocket
     # 启动一个ws服务端wscat --listen 9000，将网关启动（网关端口为9090），
     # 进行客户端连接即可wscat --connect ws://localhost:9090/echo
     - id: websocket_test
        uri: ws://localhost:9000
        order: 9000
        predicates:
        - Path=/echo