spring:
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri: https://github.com/forezp/SpringcloudConfig
          #远程仓库的文件夹地址
          search-paths: respo
          #私人仓库登录用户名和密码
          username: miles02@163.com
          password:
      #仓库分支
      label: master

  application:
    name: eureka-config-server

server:
  port: 8840
