spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.59.16:3306/spring_cloud_demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: spring_cloud_demo
    password: spring_cloud_demo
  jpa:
    hibernate:
      #第一次建表，后面使用update
      ddl-auto: update
    show-sql: true
  redis:
    host: 47.107.59.16
    port: 6379
    #password:
    #database:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8