server:
  port: 8080
spring:
  config:
    location:


#person:
#  lastName: hello
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,K2: 12}
#  lists:
#  - lisi
#  - zhaoliu
#  dog:
#    name: ะกนท
#    age: 12