server:
  port: 8080
spring:
  redis:
    database: 0
    host: 192.168.57.101
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 8
      timeout: 0
  session:
    store-type: redis